# display settings
SCREEN_WIDTH = 650
SCREEN_HEIGHT = 650
BG_COLOR = (52, 65, 87)

# ship settings
SHIP_SPEED_FACTOR = 0.4

# bullet settings
BULLETS_ALLOWED_ON_SCREEN = 4
BULLET_SPEED_FACTOR = 2
BULLET_WIDTH = 2
BULLET_HEIGHT = 12
BULLET_COLOR = (40, 140, 0)

# alien settings
ALIEN_SPEED_FACTOR = 0.175
FLEET_DIRECTION = 1
FLEET_SPEED = 10
